name: chess_timer
description: Chess Timer

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.1
  url_launcher: ^6.1.5
  flutter_form_builder: ^7.5.0
  form_builder_validators: ^8.3.0
  auto_size_text: ^3.0.0
  package_info_plus: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "static/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/fonts/
    - assets/flags/
    - assets/translations/

  fonts: 
   - family: CustomIcons
     fonts:
      - asset: assets/fonts/CustomIcons.ttf
